CREATE TABLE "executed_trades" (
	"id" text PRIMARY KEY NOT NULL,
	"signal_id" text NOT NULL,
	"account" text NOT NULL,
	"pair" text NOT NULL,
	"timeframe" text NOT NULL,
	"direction" text NOT NULL,
	"requested_lots" double precision NOT NULL,
	"requested_entry" double precision NOT NULL,
	"filled_entry" double precision,
	"stop_loss" double precision NOT NULL,
	"take_profit" double precision NOT NULL,
	"take_profit_2" double precision NOT NULL,
	"status" text NOT NULL,
	"broker_position_id" text,
	"broker_order_id" text,
	"reject_reason" text,
	"risk_pct" double precision NOT NULL,
	"attempted_at" timestamp with time zone NOT NULL,
	"filled_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "signals" (
	"id" text PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"pair" text NOT NULL,
	"direction" text NOT NULL,
	"entry" double precision NOT NULL,
	"stop_loss" double precision NOT NULL,
	"take_profit" double precision NOT NULL,
	"take_profit_2" double precision NOT NULL,
	"risk_reward" double precision NOT NULL,
	"confidence" double precision NOT NULL,
	"direction_score" double precision NOT NULL,
	"entry_score" double precision NOT NULL,
	"adx" double precision NOT NULL,
	"rsi" double precision NOT NULL,
	"tier" text NOT NULL,
	"confluences" jsonb NOT NULL,
	"session" text NOT NULL,
	"timeframe" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"zone_top" double precision,
	"zone_bottom" double precision,
	"signer_b_direction" text NOT NULL,
	"signer_b_confidence" double precision NOT NULL,
	"signer_b_ema_trend" text NOT NULL,
	"rsi_divergence" text NOT NULL,
	"supertrend_trend" text NOT NULL,
	"usd_strength_status" text NOT NULL,
	"news_status" text NOT NULL
);
